CommitMsg:
  CapitalizedSubject:
    enabled: false

  EmptyMessage:
    enabled: false

  TrailingPeriod:
    enabled: true

  TextWidth:
    enabled: false

PreCommit:
  ALL:
    on_warn: fail

  AuthorEmail:
    enabled: true

  AuthorName:
    enabled: false

  MergeConflicts:
    enabled: true

  YamlSyntax:
    enabled: true

  BundleCheck:
    enabled: true

  RuboCop:
    enabled: true

  Fasterer:
    enabled: true

  Reek:
    enabled:  false
    exclude:
      - 'db/migrate/**/*.rb'
      - 'docs/**/*.md'

  RailsSchemaUpToDate:
    enabled: true

  SlimLint:
    enabled: true

PrePush:
  ProtectedBranches:
    enabled: true
    destructive_only: true
    branches:
      - 'master'
      - 'dev'
