AllCops:
  TargetRubyVersion: 2.5.1
  Exclude:
    - db/schema.rb
    - db/seeds.rb

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Max: 80
  Exclude:
    - config/routes.rb
    - db/**/*
    - spec/*
    - spec/**/*

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 50

Style/Documentation:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/AsciiComments:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - db/**/*
    - spec/*
    - spec/**/*

Style/Lambda:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/NestedGroups:
  Max: 5
Metrics/ClassLength:
  Max: 150

Layout/EmptyLinesAroundClassBody:
  Enabled: false
Layout/EmptyLines:
  Enabled: false
Layout/SpaceInLambdaLiteral:
  Enabled: false
Layout/EmptyLinesAroundModuleBody:
  Enabled: false
Layout/EmptyLinesAroundBlockBody:
  Enabled: false

require: rubocop-rspec
